packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@milaboratories/ts-builder': ^1.0.5
  '@milaboratories/ts-configs': ^1.0.6
  '@milaboratories/build-configs': ^1.0.8
  '@platforma-sdk/workflow-tengo': ^5.5.0
  '@platforma-sdk/model': ^1.45.0
  '@platforma-sdk/ui-vue': ^1.45.0
  '@platforma-sdk/tengo-builder': ^2.3.3
  '@platforma-sdk/package-builder': ^3.10.6
  '@platforma-sdk/block-tools': ^2.6.16
  '@platforma-sdk/eslint-config': ^1.1.0
  '@platforma-sdk/blocks-deps-updater': ^2.0.0

  '@platforma-sdk/test': ^1.45.0
  '@milaboratories/helpers': ^1.12.0

  '@platforma-open/milaboratories.software-binary-collection.software-7zip': ^1.1.2

  'es-toolkit': ^1.39.10

  'vue': 3.5.13
  'vue-tsc': ^2.2.10
  '@vueuse/core': ^13.9.0

  'typescript': ~5.6.3
  'tsup': ~8.3.5
  'turbo': ^2.5.4
  'eslint': ^9.30.1

  'vite': ^6.3.5
  'vitest': ^2.1.9
  '@vitejs/plugin-vue': ^5.2.4
  'rollup-plugin-sourcemaps2': ^0.5.2

  '@changesets/cli': ^2.29.5

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.10.7
  '@platforma-open/milaboratories.samples-and-data.model': ^1.10.0
