packages:
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.45.0
  "@platforma-sdk/ui-vue": ^1.45.5
  "@platforma-sdk/workflow-tengo": ^5.5.9
  "@platforma-sdk/block-tools": ^2.6.16
  "@platforma-sdk/test": ^1.45.11
  "@platforma-sdk/tengo-builder": ^2.3.3
  "@platforma-sdk/package-builder": ^3.10.7
  "@platforma-sdk/eslint-config": ^1.1.0
  "@milaboratories/graph-maker": ^1.1.175
  "@platforma-sdk/blocks-deps-updater": ^2.0.0
  
  '@milaboratories/software-pframes-conv': ^2.2.9
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.22
  "@platforma-open/milaboratories.runenv-python-3": ^1.1.16
  
  "vue": ^3.5.12
  "vue-tsc": ^2.1.6
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.4.4

  "vite": ^5.4.11
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.1.4

  "@changesets/cli": ^2.27.9
