packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@types/node': ~24.5.2

  '@milaboratories/ts-builder': ^1.1.0
  '@milaboratories/ts-configs': ^1.1.0
  '@milaboratories/build-configs': ^1.1.0
  '@platforma-sdk/workflow-tengo': ^5.6.6
  '@platforma-sdk/model': ^1.47.5
  '@platforma-sdk/ui-vue': ^1.47.5
  '@platforma-sdk/tengo-builder': ^2.4.1
  '@platforma-sdk/package-builder': ^3.10.7
  '@platforma-sdk/block-tools': ^2.6.27
  '@platforma-sdk/eslint-config': ^1.1.0
  '@milaboratories/graph-maker': ^1.1.195
  '@milaboratories/pf-plots': ^1.1.52
  '@platforma-sdk/blocks-deps-updater': ^2.0.0
  '@milaboratories/pl-model-common': ^1.21.10

  '@platforma-sdk/test': ^1.47.6
  '@milaboratories/helpers': ^1.12.0

  '@platforma-open/milaboratories.software-binary-collection.software-7zip': ^1.1.2

  'canonicalize': ^2.1.0
  'es-toolkit': ^1.39.10

  'vue': 3.5.22
  '@vueuse/core': ^13.9.0

  'typescript': ~5.6.3
  'turbo': ^2.5.4
  'eslint': ^9.30.1

  'vite': ^6.3.5
  'vitest': ^2.1.9

  '@changesets/cli': ^2.29.5

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.10.7
  '@platforma-open/milaboratories.samples-and-data.model': ^1.10.0
