packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@types/node': ~24.5.2

  '@milaboratories/ts-builder': ^1.2.11
  '@milaboratories/ts-configs': ^1.2.1
  '@milaboratories/build-configs': ^1.5.0
  '@platforma-sdk/workflow-tengo': ^5.9.0
  '@platforma-sdk/model': ^1.58.5
  '@platforma-sdk/ui-vue': ^1.58.8
  '@platforma-sdk/tengo-builder': ^2.4.25
  '@platforma-sdk/package-builder': ^3.11.4
  '@platforma-sdk/block-tools': ^2.6.63
  '@platforma-sdk/eslint-config': ^1.2.0
  '@milaboratories/graph-maker': ^1.2.0
  '@milaboratories/pf-plots': ^1.1.65
  '@platforma-sdk/blocks-deps-updater': ^2.0.1
  '@milaboratories/pl-model-common': ^1.25.1

  '@platforma-sdk/test': ^1.58.7
  '@milaboratories/helpers': ^1.13.5

  '@platforma-open/milaboratories.software-binary-collection.software-7zip': ^1.1.2

  'canonicalize': ^2.1.0
  'es-toolkit': ^1.39.10

  'vue': 3.5.22
  '@vueuse/core': ^13.9.0

  'typescript': ~5.6.3
  'turbo': ^2.5.4
  'eslint': ^9.30.1

  'vite': ^6.3.5
  'vitest': ^2.1.9

  '@changesets/cli': ^2.29.5

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.10.7
  '@platforma-open/milaboratories.samples-and-data.model': ^1.10.0
